import { test, expect, TestHelpers } from '../playwright/fixtures';
import { MockIntegrationServer } from '../mocks/integration-server';
import { MockWorkerClient } from '../mocks/worker-client';
import { TestConstants } from './constants';
import * as crypto from 'crypto';

// Helper to sign webhooks
function signPayload(secret: string, payload: any): string {
    const hmac = crypto.createHmac('sha256', secret);
    const digest = hmac.update(JSON.stringify(payload)).digest('hex');
    return `sha256=${digest}`;
}

test.describe('Main End-to-End Flow (Mocked Infrastructure)', () => {
    let mockServer: MockIntegrationServer;
    let mockWorker: MockWorkerClient;
    let integrationId: string;
    let projectId: string;
    let projectSlug: string;

    const webhookSecret = 'test-secret';
    const mockServerUrl = `http://localhost:${TestConstants.MOCK_SERVER_PORT}`;

    test.beforeAll(async () => {
        // 1. Start Mock Integration Server (Fake GitHub)
        mockServer = new MockIntegrationServer(TestConstants.MOCK_SERVER_PORT);
        await mockServer.start();

        // 2. Start Mock Worker
        mockWorker = new MockWorkerClient(TestConstants.BACKEND_URL);
        mockWorker.start();
    });

    test.afterAll(async () => {
        await mockServer.stop();
        mockWorker.stop();
    });

    // Setup data via API to ensure correct configuration (BaseURL injection)
    test('Setup: Create Integration and Project', async ({ request }) => {
        // Create Integration with custom Base URL pointing to our Mock Server
        console.log(`Connecting to backend at ${TestConstants.BACKEND_URL}`);
        try {
            const integrationRes = await request.post(`${TestConstants.BACKEND_URL}/api/integrations`, {
                data: {
                    type: 'github',
                    name: 'E2E Mock GitHub',
                    config: {
                        baseUrl: mockServerUrl, // <--- CRITICAL: Point to mock server
                        owner: 'test-org',
                        repo: 'test-repo',
                        token: 'mock-token',
                        webhookSecret: webhookSecret,
                        labels: ['test-label']
                    }
                }
            });
            console.log(`Integration creation status: ${integrationRes.status()}`);
            if (!integrationRes.ok()) {
                console.error('Integration creation failed:', await integrationRes.text());
            }
            expect(integrationRes.ok()).toBeTruthy();
            const integration = await integrationRes.json();
            integrationId = integration.id;
        } catch (e) {
            console.error('Integration creation exception:', e);
            throw e;
        }

        // Create Project
        const name = `E2E Flow ${TestHelpers.generateUniqueId()}`;
        const projectRes = await request.post(`${TestConstants.BACKEND_URL}/api/projects`, {
            data: {
                name: name,
                description: 'Auto-generated by E2E tests',
                repositoryUrls: ['https://github.com/test-org/test-repo'],
                autoFixEnabled: true,
                autoFixTags: ['auto-fix', 'bug'],
                agentInstructions: 'Fix the bug.',
                ticketSystemId: integrationId // Link the integration
            }
        });
        expect(projectRes.ok()).toBeTruthy();
        const project = await projectRes.json();
        projectId = project.id;
        projectSlug = project.slug;

        // Link integration to project (if separate step needed, usually covered by create or separate link call)
        // Assuming the API handles it or we do it here:
        // await request.post(...link...)
        // Based on `createProject` usually linking, we'll verify in UI.
    });

    test('Step 1-7: Webhook Ingestion -> Platform Ticket Creation', async ({ page, request }) => {
        // Simulate GitHub Webhook
        // This covers "Webhook delivered" and "Platform ticket auto-created"

        // We navigate to the project to establish "socket" connection or just to view the result
        await page.goto(`/project/${projectSlug}/tickets`);

        const issueNumber = 12345;
        const payload = {
            action: 'opened',
            issue: {
                number: issueNumber,
                title: 'Critical Bug in Login',
                body: 'Users cannot login.',
                labels: [{ name: 'bug' }, { name: 'auto-fix' }]
            },
            repository: {
                full_name: 'test-org/test-repo'
            }
        };

        const signature = signPayload(webhookSecret, payload);

        // Send Webhook to Backend
        const response = await request.post(`${TestConstants.BACKEND_URL}/api/webhooks/github`, {
            data: payload,
            headers: {
                'X-GitHub-Event': 'issues',
                'X-Hub-Signature-256': signature // Viberator backend will verify this
            }
        });

        expect(response.status()).toBe(200);

        // Verify Ticket Appears in UI
        await expect(page.getByText('Critical Bug in Login')).toBeVisible({ timeout: 10000 });

        // Verify Ticket Status is "Queued" or "Processing" (since Auto-Fix is on)
        // You might see a status badge
    });

    test('Step 8-15: Job Execution (Mock Worker)', async ({ page }) => {
        // The Mock Worker is running in the background.
        // It should:
        // 1. Pick up the job (Auto-fix triggered by the webhook)
        // 2. "Process" it (wait 500ms)
        // 3. Post a result pointing to the Mock Server

        // Wait for the UI to update to "Completed"
        // This implicitly validates: Job Created -> Worker Picked Up -> Worker Completed

        // We stay on the tickets page or click into the ticket
        await page.getByText('Critical Bug in Login').click();

        // Wait for "Completed" status
        await expect(page.getByText(/Completed|Fixed/i)).toBeVisible({ timeout: 15000 });

        // Validate a PR link exists
        const prLink = page.getByRole('link', { name: /pull request/i }).or(page.locator('a[href*="/mock/pull"]'));
        await expect(prLink).toBeVisible();

        // Get the href and verify it points to our mock server
        const href = await prLink.getAttribute('href');
        expect(href).toContain(mockServerUrl);
    });

    test('Step 16-18: Verify Feedback to Integration (Mock Server)', async () => {
        // Verify the mock server received the "Create PR" and "Post Comment" calls
        const prRequests = mockServer.requests.pullRequests;
        expect(prRequests.length).toBeGreaterThan(0);
        expect(prRequests[0].title).toBeTruthy();

        // Verify comment on issue
        const commentRequests = mockServer.requests.comments;
        expect(commentRequests.length).toBeGreaterThan(0);
        // The worker (or backend) should have posted a comment saying "I fixed it"
    });
});
