FROM public.ecr.aws/lambda/nodejs:24 AS builder

WORKDIR /app
COPY apps/slack-app/package*.json ./
RUN npm install
COPY apps/slack-app/tsconfig.json ./tsconfig.json
COPY apps/slack-app/src ./src
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:24

WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist

CMD ["dist/lambda.handler"]
