import { JOB_FAILURE_CODE, type TicketWorkflowPhase } from "@viberglass/types";

/**
 * What the demo workspace contains: one space with tasks at every stage a
 * product leader meets today (ADR 0002, J1's "Explore a demo workspace"). All
 * of it is sample data; the repository and pull request links are fictional.
 */

export const DEMO_SPACE_NAME = "Demo: Acme storefront";
export const DEMO_REPOSITORY = "https://example.com/acme/storefront";
export const DEMO_RUNNER_NAME = "Demo agent (sample data)";

export const DEMO_MEMBERS = [
  { name: "Tomi Laine", email: "tomi.laine@demo.viberglass.invalid" },
  { name: "Aino Virtanen", email: "aino.virtanen@demo.viberglass.invalid" },
] as const;

export interface DemoDocument {
  phase: TicketWorkflowPhase;
  content: string;
  approval: "approval_requested" | "approved";
}

export interface DemoRun {
  phase: TicketWorkflowPhase;
  outcome: "completed" | "failed";
  /** Hours before now that it finished. */
  hoursAgo: number;
  failureCode?: string;
  errorMessage?: string;
}

export interface DemoTask {
  title: string;
  description: string;
  phase: TicketWorkflowPhase;
  documents: DemoDocument[];
  runs: DemoRun[];
  pullRequestUrl?: string;
}

const RESEARCH_GIFT_NOTE = `# Research: gift note at checkout

## What exists today
- Checkout is three steps: cart → address → payment (\`src/checkout/steps\`).
- Orders already carry free-text \`deliveryInstructions\`, stored with the order and shown on the packing slip.

## What a gift note needs
- A short message (max 200 characters) entered on the address step.
- Printed on the packing slip, never on the invoice.

## Risks
- Packing slips are generated by the warehouse service; its template needs one new field.
`;

const PLAN_GIFT_NOTE = `# Plan: gift note at checkout

1. Add \`giftNote\` (optional, ≤ 200 characters) to the order model and API.
2. Add a "Add a gift note" toggle and text field to the address step.
3. Pass \`giftNote\` to the warehouse service and show it on the packing slip.
4. Tests: order API validation, checkout step, packing slip template.

Out of scope: gift wrapping, hiding prices on the slip.
`;

const RESEARCH_SEARCH = `# Research: how search indexing works

- Products are indexed nightly by \`jobs/reindex-products\`, and on every product save through \`ProductSavedListener\`.
- The index lives in OpenSearch; the mapping is in \`search/mapping.json\`.
- Stock changes don't trigger a reindex, which is why sold-out products keep showing for up to a day.

**Suggested next step:** reindex on stock changes too, or filter sold-out products at query time.
`;

const RESEARCH_DELIVERY = `# Research: delivery estimates on product pages

- Carriers expose estimates through the existing \`ShippingQuoteService\`.
- Product pages can call it with the visitor's postcode, falling back to the store's default region.
`;

const PLAN_DELIVERY = `# Plan: delivery estimates on product pages

1. Add \`GET /api/products/:id/delivery-estimate\` using \`ShippingQuoteService\`.
2. Show "Arrives by …" under the price, with the postcode the estimate is for.
3. Cache estimates per postcode area for an hour.
`;

export const DEMO_TASKS: DemoTask[] = [
  {
    title: "Add a gift note to checkout",
    description: "Customers keep asking to include a personal message when an order is a gift.",
    phase: "planning",
    documents: [
      { phase: "research", content: RESEARCH_GIFT_NOTE, approval: "approved" },
      { phase: "planning", content: PLAN_GIFT_NOTE, approval: "approval_requested" },
    ],
    runs: [
      { phase: "research", outcome: "completed", hoursAgo: 26 },
      { phase: "planning", outcome: "completed", hoursAgo: 3 },
    ],
  },
  {
    title: "Show delivery estimates on product pages",
    description: "Show when an item would arrive, so fewer people leave the page to check.",
    phase: "execution",
    documents: [
      { phase: "research", content: RESEARCH_DELIVERY, approval: "approved" },
      { phase: "planning", content: PLAN_DELIVERY, approval: "approved" },
    ],
    runs: [
      { phase: "research", outcome: "completed", hoursAgo: 72 },
      { phase: "planning", outcome: "completed", hoursAgo: 50 },
      { phase: "execution", outcome: "completed", hoursAgo: 20 },
    ],
    pullRequestUrl: "https://example.com/acme/storefront/pull/128",
  },
  {
    title: "Explain how search indexing works",
    description: "Sold-out products stay in search results for a day. Why, and what would fix it?",
    phase: "research",
    documents: [{ phase: "research", content: RESEARCH_SEARCH, approval: "approval_requested" }],
    runs: [{ phase: "research", outcome: "completed", hoursAgo: 6 }],
  },
  {
    title: "Fix rounding in cart totals",
    description: "Totals are sometimes one cent off when several discounts apply.",
    phase: "research",
    documents: [],
    runs: [
      {
        phase: "research",
        outcome: "failed",
        hoursAgo: 1,
        failureCode: JOB_FAILURE_CODE.AGENT_QUOTA_EXHAUSTED,
        errorMessage: "The model provider refused the request: the account has no credit left.",
      },
    ],
  },
  {
    title: "Speed up image loading on the home page",
    description: "The hero and category images load slowly on mobile.",
    phase: "research",
    documents: [],
    runs: [],
  },
];
