import { Logger } from "winston";
import { simpleGit, SimpleGit } from "simple-git";
import * as path from "path";
import axios from "axios";
import { SCMAuthFactory } from "../scm";

export class GitService {
  constructor(private logger: Logger) {}

  /**
   * Clone repository with automatic SCM authentication using simple-git
   */
  public async cloneRepository(
    repoUrl: string,
    branch: string,
    workDir: string,
  ): Promise<void> {
    try {
      this.logger.info("Cloning repository", { repoUrl, branch });

      // Use SCM authentication factory to get authenticated URL
      const authenticatedUrl = SCMAuthFactory.authenticateUrl(repoUrl);

      if (authenticatedUrl !== repoUrl) {
        this.logger.info("Using authenticated URL for repository clone");
      } else {
        this.logger.warn(
          "No authentication applied - URL unchanged. Check if token is set.",
        );
      }

      const git = simpleGit({ baseDir: workDir });
      const repoPath = path.join(workDir, "repo");

      // Disable credential prompting completely
      await git.clone(authenticatedUrl, repoPath, [
        "--branch",
        branch,
        "--single-branch",
        "-c",
        "core.askPass=",
        "-c",
        "credential.helper=",
      ]);

      this.logger.debug("Repository cloned successfully", { repoUrl, branch });
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Git clone failed", { error: errorMessage });
      throw new Error(`Git clone failed: ${errorMessage}`);
    }
  }

  /**
   * Parse changed files from git diff
   */
  public async getChangedFiles(repoDir: string): Promise<string[]> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      const result = await git.diff(["--name-only"]);
      return result.split("\n").filter((line) => line.trim().length > 0);
    } catch (error) {
      this.logger.warn("Could not get changed files", { error });
      return [];
    }
  }

  /**
   * Create a new branch using simple-git
   */
  public async createBranch(
    repoDir: string,
    branchName: string,
  ): Promise<void> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      await git.checkoutLocalBranch(branchName);
      this.logger.info("Branch created", { branchName });
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Failed to create branch", { error: errorMessage });
      throw new Error(`Failed to create branch: ${errorMessage}`);
    }
  }

  /**
   * Commit changes using simple-git
   */
  public async commitChanges(
    repoDir: string,
    message: string,
  ): Promise<string> {
    try {
      const git = simpleGit({ baseDir: repoDir });

      // Check if there are changes to commit
      const status = await git.status();
      if (status.files.length === 0) {
        this.logger.info("No changes to commit");
        const log = await git.log({ maxCount: 1 });
        return log.latest?.hash || "";
      }

      // Stage all changes
      await git.add(".");

      // Commit with message
      const commitMessage = `fix: ${message}\n\n🤖 Generated by Vibug Viberator`;
      await git.commit(commitMessage);

      // Get commit hash
      const log = await git.log({ maxCount: 1 });
      const commitHash = log.latest?.hash || "";

      this.logger.info("Changes committed", { commitHash });
      return commitHash;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Failed to commit changes", { error: errorMessage });
      throw new Error(`Failed to commit changes: ${errorMessage}`);
    }
  }

  /**
   * Push branch using simple-git
   */
  public async pushBranch(repoDir: string, branchName: string): Promise<void> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      await git.push("origin", branchName, ["--set-upstream"]);
      this.logger.info("Branch pushed", { branchName });
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Failed to push branch", { error: errorMessage });
      throw new Error(`Failed to push branch: ${errorMessage}`);
    }
  }

  /**
   * Create a pull request using the GitHub REST API
   */
  public async createPullRequest(
    repoDir: string,
    sourceBranch: string,
    targetBranch: string,
    title: string,
  ): Promise<string> {
    try {
      const { owner, repo } = await this.getRepoMetadata(repoDir);
      // Use SCMAuthFactory to get the token
      const token = SCMAuthFactory.getProvider(
        `https://github.com/${await this.getRepoMetadata(repoDir).then((m) => `${m.owner}/${m.repo}`)}`,
      )?.getToken();

      if (!token) {
        throw new Error(
          "Unable to retrieve authentication token from SCMAuthFactory",
        );
      }
      if (!token) {
        throw new Error("GITHUB_TOKEN is not defined in environment variables");
      }

      this.logger.info("Creating pull request via GitHub API", {
        repo: `${owner}/${repo}`,
        head: sourceBranch,
        base: targetBranch,
      });

      const response = await axios.post(
        `https://api.github.com/repos/${owner}/${repo}/pulls`,
        {
          title: title,
          head: sourceBranch,
          base: targetBranch,
          body: "🤖 Automated fix by Vibug Viberator\n\nThis PR was generated automatically.",
          maintainer_can_modify: true,
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
          },
        },
      );

      const prUrl = response.data.html_url;
      this.logger.info("Pull request successfully created", {
        prUrl,
        id: response.data.id,
      });
      return prUrl;
    } catch (error: any) {
      let errorMessage = "Unknown error";
      let details = null;

      if (axios.isAxiosError(error)) {
        errorMessage = error.response?.data?.message || error.message;
        details = error.response?.data?.errors;

        // Handle specific case: PR already exists
        if (
          error.response?.status === 422 &&
          details?.[0]?.message?.includes("A pull request already exists")
        ) {
          this.logger.warn("Pull request already exists for this branch");
          return this.getExistingPullRequestUrl(repoDir, sourceBranch);
        }
      } else if (error instanceof Error) {
        errorMessage = error.message;
      }

      this.logger.error("Failed to create pull request via API", {
        error: errorMessage,
        details,
      });
      throw new Error(`GitHub PR Creation Failed: ${errorMessage}`);
    }
  }

  /**
   * Internal helper to extract owner and repo name from git remote
   */
  private async getRepoMetadata(
    repoDir: string,
  ): Promise<{ owner: string; repo: string }> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      const remotes = await git.getRemotes(true);
      const origin = remotes.find((r) => r.name === "origin") || remotes[0];

      if (!origin) {
        throw new Error("No git remotes found");
      }

      // Regex to handle both HTTPS and SSH formats
      // e.g., https://github.com/owner/repo.git OR git@github.com:owner/repo.git
      const remoteUrl = origin.refs.push;
      const match = remoteUrl.match(/github\.com[:/](.+)\/(.+?)(\.git)?$/);

      if (!match) {
        throw new Error(`Could not parse owner/repo from URL: ${remoteUrl}`);
      }

      return {
        owner: match[1],
        repo: match[2],
      };
    } catch (error) {
      this.logger.error("Failed to parse repository metadata", { error });
      throw error;
    }
  }

  /**
   * Fallback to find an existing PR URL if creation fails because it already exists
   */
  private async getExistingPullRequestUrl(
    repoDir: string,
    head: string,
  ): Promise<string> {
    const { owner, repo } = await this.getRepoMetadata(repoDir);
    const token = process.env.GITHUB_TOKEN;

    const response = await axios.get(
      `https://api.github.com/repos/${owner}/${repo}/pulls`,
      {
        params: { head: `${owner}:${head}`, state: "open" },
        headers: { Authorization: `Bearer ${token}` },
      },
    );

    return (
      response.data[0]?.html_url || `https://github.com/${owner}/${repo}/pulls`
    );
  }
}
