import { Logger } from "winston";
import { simpleGit, SimpleGit } from "simple-git";
import * as path from "path";
import axios from "axios";
import { SCMAuthFactory } from "../scm";
import { GitConfig } from "../types";

interface PullRequestOptions {
  sourceRepositoryUrl?: string;
  destinationRepositoryUrl?: string;
}

class GitService {
  private gitConfig: GitConfig;

  constructor(
    private logger: Logger,
    gitConfig?: GitConfig,
  ) {
    this.gitConfig = gitConfig || {
      userName: process.env.GIT_USER_NAME || "Vibes Viber",
      userEmail: process.env.GIT_USER_EMAIL || "viberator@viberglass.io",
    };
  }

  private async initializeGitConfig(repoDir: string): Promise<SimpleGit> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      await git.addConfig("user.name", this.gitConfig.userName, false, "local");
      await git.addConfig(
        "user.email",
        this.gitConfig.userEmail,
        false,
        "local",
      );
      this.logger.debug("Git user identity configured", {
        userName: this.gitConfig.userName,
        userEmail: this.gitConfig.userEmail,
        repoDir,
      });
      return git;
    } catch (error) {
      this.logger.warn("Failed to configure git user identity", { error });
      return simpleGit({ baseDir: repoDir });
    }
  }

  /**
   * Clone repository with automatic SCM authentication using simple-git
   */
  public async cloneRepository(
    repoUrl: string,
    branch: string,
    workDir: string,
    scmToken?: string,
  ): Promise<void> {
    try {
      this.logger.info("Cloning repository", { repoUrl, branch });

      // Use SCM authentication factory to get authenticated URL
      const authenticatedUrl = SCMAuthFactory.authenticateUrl(repoUrl, scmToken);

      if (authenticatedUrl !== repoUrl) {
        this.logger.info("Using authenticated URL for repository clone");
      } else {
        this.logger.warn(
          "No authentication applied - URL unchanged. Check if token is set.",
        );
      }

      const git = simpleGit({ baseDir: workDir });
      const repoPath = path.join(workDir, "repo");

      await git.env("GIT_TERMINAL_PROMPT", "0").clone(authenticatedUrl, repoPath, [
        "--branch",
        branch,
        "--single-branch",
      ]);

      this.logger.debug("Repository cloned successfully", { repoUrl, branch });
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Git clone failed", { error: errorMessage });
      throw new Error(`Git clone failed: ${errorMessage}`);
    }
  }

  /**
   * Parse changed files from git diff
   */
  public async getChangedFiles(repoDir: string): Promise<string[]> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      const result = await git.diff(["--name-only"]);
      return result.split("\n").filter((line) => line.trim().length > 0);
    } catch (error) {
      this.logger.warn("Could not get changed files", { error });
      return [];
    }
  }

  /**
   * Create a new branch using simple-git
   */
  public async createBranch(
    repoDir: string,
    branchName: string,
  ): Promise<void> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      await git.checkoutLocalBranch(branchName);
      this.logger.info("Branch created", { branchName });
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Failed to create branch", { error: errorMessage });
      throw new Error(`Failed to create branch: ${errorMessage}`);
    }
  }

  /**
   * Commit changes using simple-git
   */
  public async commitChanges(
    repoDir: string,
    message: string,
  ): Promise<string> {
    try {
      const git = await this.initializeGitConfig(repoDir);

      // Check if there are changes to commit
      const status = await git.status();
      if (status.files.length === 0) {
        this.logger.info("No changes to commit");
        const log = await git.log({ maxCount: 1 });
        return log.latest?.hash || "";
      }

      // Stage all changes
      await git.add(".");

      // Commit with message
      const commitMessage = `fix: ${message}\n\n🤖 Generated by Viberator`;
      await git.commit(commitMessage);

      // Get commit hash
      const log = await git.log({ maxCount: 1 });
      const commitHash = log.latest?.hash || "";

      this.logger.info("Changes committed", { commitHash });
      return commitHash;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Failed to commit changes", { error: errorMessage });
      throw new Error(`Failed to commit changes: ${errorMessage}`);
    }
  }

  /**
   * Push branch using simple-git
   */
  public async pushBranch(repoDir: string, branchName: string, scmToken?: string): Promise<void> {
    try {
      // Re-authenticate the remote URL if a token is provided
      if (scmToken) {
        const git = simpleGit({ baseDir: repoDir });
        const remotes = await git.getRemotes(true);
        const origin = remotes.find((r) => r.name === "origin");
        if (origin) {
          const currentUrl = origin.refs.push || origin.refs.fetch;
          if (currentUrl) {
            const authenticatedUrl = SCMAuthFactory.authenticateUrl(currentUrl, scmToken);
            if (authenticatedUrl !== currentUrl) {
              await git.remote(["set-url", "origin", authenticatedUrl]);
            }
          }
        }
      }

      const git = simpleGit({ baseDir: repoDir });
      await git.push("origin", branchName, ["--set-upstream"]);
      this.logger.info("Branch pushed", { branchName });
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      this.logger.error("Failed to push branch", { error: errorMessage });
      throw new Error(`Failed to push branch: ${errorMessage}`);
    }
  }

  /**
   * Create a pull request using the GitHub REST API
   */
  public async createPullRequest(
    repoDir: string,
    sourceBranch: string,
    targetBranch: string,
    title: string,
    description?: string,
    options?: PullRequestOptions,
    scmToken?: string,
  ): Promise<string> {
    const sourceRepo = options?.sourceRepositoryUrl
      ? this.getRepoMetadataFromUrl(options.sourceRepositoryUrl)
      : await this.getRepoMetadata(repoDir);
    const destinationRepo = options?.destinationRepositoryUrl
      ? this.getRepoMetadataFromUrl(options.destinationRepositoryUrl)
      : sourceRepo;
    const isCrossRepositoryPullRequest =
      sourceRepo.owner !== destinationRepo.owner ||
      sourceRepo.repo !== destinationRepo.repo;
    const isSameOwnerCrossRepositoryPullRequest =
      isCrossRepositoryPullRequest &&
      sourceRepo.owner === destinationRepo.owner;
    const headRef = isCrossRepositoryPullRequest
      ? `${sourceRepo.owner}:${sourceBranch}`
      : sourceBranch;
    const existingPullRequestHeadRef = `${sourceRepo.owner}:${sourceBranch}`;
    let token: string | undefined;

    const providerLookupUrl =
      options?.sourceRepositoryUrl ||
      options?.destinationRepositoryUrl ||
      `https://github.com/${sourceRepo.owner}/${sourceRepo.repo}`;
    try {
      token = scmToken || SCMAuthFactory.getProvider(providerLookupUrl)?.getToken();

      if (!token) {
        throw new Error(
          "Unable to retrieve authentication token from SCMAuthFactory",
        );
      }

      this.logger.info("Creating pull request via GitHub API", {
        sourceRepo: `${sourceRepo.owner}/${sourceRepo.repo}`,
        destinationRepo: `${destinationRepo.owner}/${destinationRepo.repo}`,
        head: headRef,
        base: targetBranch,
        headRepo: isSameOwnerCrossRepositoryPullRequest
          ? sourceRepo.repo
          : undefined,
      });

      // Use provided description or fall back to default
      const prBody = description
        ? `${description}\n\n---\n🤖 Generated by Viberator`
        : "🤖 Automated fix by Viberator\n\nThis PR was generated automatically.";
      const pullRequestPayload: {
        title: string;
        head: string;
        base: string;
        body: string;
        maintainer_can_modify: boolean;
        head_repo?: string;
      } = {
        title: title,
        head: headRef,
        base: targetBranch,
        body: prBody,
        maintainer_can_modify: true,
      };

      // GitHub requires head_repo for cross-repo PRs within the same owner/org.
      if (isSameOwnerCrossRepositoryPullRequest) {
        pullRequestPayload.head_repo = sourceRepo.repo;
      }

      const response = await axios.post(
        `https://api.github.com/repos/${destinationRepo.owner}/${destinationRepo.repo}/pulls`,
        pullRequestPayload,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
          },
        },
      );

      const prUrl = response.data.html_url;
      this.logger.info("Pull request successfully created", {
        prUrl,
        id: response.data.id,
      });
      return prUrl;
    } catch (error) {
      let errorMessage = "Unknown error";
      let details: unknown = null;
      if (axios.isAxiosError(error)) {
        const responseData = error.response?.data as
          | { message?: string; errors?: unknown }
          | undefined;
        errorMessage = responseData?.message || error.message;
        details = responseData?.errors;

        // Handle specific case: PR already exists
        if (
          error.response?.status === 422 &&
          Array.isArray(details) &&
          details.some(
            (detail) =>
              typeof detail?.message === "string" &&
              detail.message.includes("A pull request already exists"),
          )
        ) {
          const existingPullRequestToken =
            token || SCMAuthFactory.getProvider(providerLookupUrl)?.getToken();
          if (!existingPullRequestToken) {
            throw new Error(
              "Unable to retrieve authentication token from SCMAuthFactory",
            );
          }

          this.logger.warn("Pull request already exists for this branch");
          return this.getExistingPullRequestUrl(
            destinationRepo,
            existingPullRequestHeadRef,
            existingPullRequestToken,
          );
        }

        if (Array.isArray(details)) {
          const detailMessages = details
            .map((detail) => {
              if (typeof detail?.message === "string") {
                return detail.message;
              }
              if (typeof detail?.code === "string") {
                return detail.code;
              }
              return null;
            })
            .filter((message): message is string => Boolean(message));

          if (detailMessages.length > 0) {
            errorMessage = `${errorMessage}: ${detailMessages.join("; ")}`;
          }
        }
      } else if (error instanceof Error) {
        errorMessage = error.message;
      }

      this.logger.error("Failed to create pull request via API", {
        error: errorMessage,
        details,
      });
      throw new Error(`GitHub PR Creation Failed: ${errorMessage}`);
    }
  }

  /**
   * Internal helper to extract owner and repo name from git remote
   */
  private async getRepoMetadata(
    repoDir: string,
  ): Promise<{ owner: string; repo: string }> {
    try {
      const git = simpleGit({ baseDir: repoDir });
      const remotes = await git.getRemotes(true);
      const origin = remotes.find((r) => r.name === "origin") || remotes[0];

      if (!origin) {
        throw new Error("No git remotes found");
      }

      // Regex to handle both HTTPS and SSH formats
      // e.g., https://github.com/owner/repo.git OR git@github.com:owner/repo.git
      const remoteUrl = origin.refs.push;
      const match = remoteUrl.match(
        /github\.com[:/]([^/]+)\/([^/]+?)(?:\.git)?$/i,
      );

      if (!match) {
        throw new Error(`Could not parse owner/repo from URL: ${remoteUrl}`);
      }

      return {
        owner: match[1],
        repo: match[2],
      };
    } catch (error) {
      this.logger.error("Failed to parse repository metadata", { error });
      throw error;
    }
  }

  /**
   * Fallback to find an existing PR URL if creation fails because it already exists
   */
  private async getExistingPullRequestUrl(
    destinationRepo: { owner: string; repo: string },
    head: string,
    token: string,
  ): Promise<string> {
    const response = await axios.get(
      `https://api.github.com/repos/${destinationRepo.owner}/${destinationRepo.repo}/pulls`,
      {
        params: { head, state: "open" },
        headers: { Authorization: `Bearer ${token}` },
      },
    );

    return (
      response.data[0]?.html_url ||
      `https://github.com/${destinationRepo.owner}/${destinationRepo.repo}/pulls`
    );
  }

  private getRepoMetadataFromUrl(repoUrl: string): {
    owner: string;
    repo: string;
  } {
    const match = repoUrl.match(/github\.com[:/]([^/]+)\/([^/]+?)(?:\.git)?$/i);

    if (!match) {
      throw new Error(`Could not parse owner/repo from URL: ${repoUrl}`);
    }

    return {
      owner: match[1],
      repo: match[2],
    };
  }
}

export default GitService;
