import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import {
  pullRequestBody,
  resolvePullRequestDescription,
  resolvePullRequestTitle,
} from "./pullRequestContent";

describe("pullRequestContent", () => {
  let repoDir: string;

  beforeEach(() => {
    repoDir = fs.mkdtempSync(path.join(os.tmpdir(), "pr-content-"));
  });

  afterEach(() => {
    fs.rmSync(repoDir, { recursive: true, force: true });
  });

  test("uses and removes agent-generated PR title file", () => {
    const titlePath = path.join(repoDir, "PR_TITLE.md");
    fs.writeFileSync(titlePath, "  ## Improve login UX.  ");

    const title = resolvePullRequestTitle(repoDir, "ignored");

    expect(title).toBe("Improve login UX");
    expect(fs.existsSync(titlePath)).toBe(false);
  });

  test("builds fallback PR title when no generated file exists", () => {
    const title = resolvePullRequestTitle(
      repoDir,
      "BUG DESCRIPTION:\nFix blank page on dashboard load.",
    );

    expect(title).toBe("fix: Fix blank page on dashboard load");
  });

  test("uses and removes agent-generated PR description file", () => {
    const descriptionPath = path.join(repoDir, "PR_DESCRIPTION.md");
    fs.writeFileSync(descriptionPath, "## Summary\nAgent-authored description");

    const description = resolvePullRequestDescription({
      repoDir,
      task: "ignored",
      changedFiles: [],
      testsWereRequested: false,
    });

    expect(description).toBe("## Summary\nAgent-authored description");
    expect(fs.existsSync(descriptionPath)).toBe(false);
  });

  test("builds fallback PR description when no generated file exists", () => {
    const description = resolvePullRequestDescription({
      repoDir,
      task: "Fix the webhook retry loop.",
      changedFiles: ["src/webhook/retry.ts"],
      testsWereRequested: true,
    });

    expect(description).toContain("## Summary");
    expect(description).toContain("Fix the webhook retry loop.");
    expect(description).toContain("- `src/webhook/retry.ts`");
    expect(description).toContain("run relevant tests");
  });

  const renderedPrompt = [
    "You are an expert software engineer tasked with fixing a bug or implementing a feature.",
    "<current-plan>",
    "x".repeat(20_000),
    "</current-plan>",
  ].join("\n");

  test("titles a ticket run's fallback PR after the ticket, not the prompt", () => {
    const title = resolvePullRequestTitle(repoDir, renderedPrompt, {
      title: "Price refresh reports success but displayed pricing never changes",
    });

    expect(title).toBe("fix: Price refresh reports success but displayed pricing never changes");
  });

  test("describes a ticket run's fallback PR from the ticket, never the prompt", () => {
    const description = resolvePullRequestDescription({
      repoDir,
      task: renderedPrompt,
      ticket: { title: "Price refresh never reaches the UI", description: "Running the script changes nothing on screen." },
      changedFiles: ["scripts/update-prices.js"],
      testsWereRequested: false,
    });

    expect(description).toContain("## Summary\nPrice refresh never reaches the UI");
    expect(description).toContain("## Problem\nRunning the script changes nothing on screen.");
    expect(description).not.toContain("You are an expert");
    expect(description).not.toContain("current-plan");
  });

  test("leaves out the problem section for a ticket with no description", () => {
    const description = resolvePullRequestDescription({
      repoDir,
      task: renderedPrompt,
      ticket: { title: "Price refresh never reaches the UI", description: "" },
      changedFiles: [],
      testsWereRequested: false,
    });

    expect(description).not.toContain("## Problem");
    expect(description.length).toBeLessThan(1000);
  });

  test("caps the problem a run without a ticket quotes from its task", () => {
    const description = resolvePullRequestDescription({
      repoDir,
      task: renderedPrompt,
      changedFiles: [],
      testsWereRequested: false,
    });

    expect(description.length).toBeLessThan(3000);
    expect(description).toContain("…");
  });
});

describe("pullRequestBody", () => {
  it("signs a description", () => {
    expect(pullRequestBody("Fixes login")).toBe("Fixes login\n\n---\n🤖 Generated by Viberator");
  });

  it("has a default body without one", () => {
    expect(pullRequestBody()).toBe("🤖 Automated fix by Viberator\n\nThis PR was generated automatically.");
  });
});
