import agentPluginCatalog from './agentPluginCatalog.json'
import { SUPPORTED_AGENT_TYPES, type AgentType } from './clanker'

/** A harness this build includes, as its plugin describes it. */
export interface AgentCatalogEntry {
  agent: AgentType
  label: string
  description: string
  /** Path the frontend serves the logo from. */
  logo: string | null
  /** New runners get this harness unless they choose another. */
  isDefault: boolean
  /** Only for tests: accepted, never offered. */
  testOnly: boolean
  /** Harnesses with a lower rank run a custom endpoint first; null ones come last. */
  endpointRank: number | null
}

function toEntry(entry: (typeof agentPluginCatalog)[number]): AgentCatalogEntry[] {
  // A harness the platform's own lists don't know yet can't be selected.
  const agent = SUPPORTED_AGENT_TYPES.find((type) => type === entry.agent)
  if (!agent) return []
  return [
    {
      agent,
      label: entry.label,
      description: entry.description,
      logo: entry.logo,
      isDefault: entry.default,
      testOnly: entry.testOnly,
      endpointRank: entry.endpointRank,
    },
  ]
}

/** The harnesses in this build, in the order the build config lists them. Generated by `npm run generate:catalog`. */
export const AGENT_CATALOG: readonly AgentCatalogEntry[] = agentPluginCatalog.flatMap(toEntry)

const catalogByAgent = new Map<string, AgentCatalogEntry>(AGENT_CATALOG.map((entry) => [entry.agent, entry]))

export function getAgentCatalogEntry(agent: string): AgentCatalogEntry | undefined {
  return catalogByAgent.get(agent)
}

/** The supported harnesses this build includes; new runners can only use these. */
export const AVAILABLE_AGENT_TYPES: AgentType[] = AGENT_CATALOG.map((entry) => entry.agent)

function findDefaultAgent(): AgentType {
  const entry = AGENT_CATALOG.find((candidate) => candidate.isDefault)
  if (!entry) throw new Error('The agent catalog has no default harness. Check defaultAgent in viberglass.plugins.json.')
  return entry.agent
}

export const DEFAULT_AGENT_TYPE: AgentType = findDefaultAgent()

export const AGENT_LABELS: Readonly<Record<string, string>> = Object.fromEntries(
  AGENT_CATALOG.map((entry) => [entry.agent, entry.label]),
)

export function isTestOnlyAgent(agent: string): boolean {
  return getAgentCatalogEntry(agent)?.testOnly === true
}

export interface AgentOption {
  value: AgentType
  label: string
  description: string
  logo: string | null
}

/** The harnesses a person can pick for a runner. */
export const AGENT_OPTIONS: AgentOption[] = AGENT_CATALOG.filter((entry) => !entry.testOnly).map((entry) => ({
  value: entry.agent,
  label: entry.label,
  description: entry.description,
  logo: entry.logo,
}))

/** A harness left out of this build shows as its id. */
export function getAgentLabel(agent?: string | null): string {
  return AGENT_LABELS[agent || DEFAULT_AGENT_TYPE] ?? agent ?? DEFAULT_AGENT_TYPE
}
