import { DomainError } from "./DomainError";

export const CLAW_SERVICE_ERROR_CODE = {
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  SCHEDULE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  EXECUTION_NOT_FOUND: "EXECUTION_NOT_FOUND",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  CLANKER_NOT_FOUND: "CLANKER_NOT_FOUND",
  INVALID_SCHEDULE_TYPE: "INVALID_SCHEDULE_TYPE",
  INVALID_INTERVAL_EXPRESSION: "INVALID_INTERVAL_EXPRESSION",
  INVALID_CRON_EXPRESSION: "INVALID_CRON_EXPRESSION",
  SCHEDULE_ALREADY_ACTIVE: "SCHEDULE_ALREADY_ACTIVE",
  SCHEDULE_ALREADY_PAUSED: "SCHEDULE_ALREADY_PAUSED",
  SCHEDULE_HAS_ACTIVE_EXECUTIONS: "SCHEDULE_HAS_ACTIVE_EXECUTIONS",
} as const;

export type ClawServiceErrorCode =
  (typeof CLAW_SERVICE_ERROR_CODE)[keyof typeof CLAW_SERVICE_ERROR_CODE];

const DEFAULT_STATUS_BY_CODE: Record<ClawServiceErrorCode, number> = {
  [CLAW_SERVICE_ERROR_CODE.TEMPLATE_NOT_FOUND]: 404,
  [CLAW_SERVICE_ERROR_CODE.SCHEDULE_NOT_FOUND]: 404,
  [CLAW_SERVICE_ERROR_CODE.EXECUTION_NOT_FOUND]: 404,
  [CLAW_SERVICE_ERROR_CODE.PROJECT_NOT_FOUND]: 404,
  [CLAW_SERVICE_ERROR_CODE.CLANKER_NOT_FOUND]: 404,
  [CLAW_SERVICE_ERROR_CODE.INVALID_SCHEDULE_TYPE]: 400,
  [CLAW_SERVICE_ERROR_CODE.INVALID_INTERVAL_EXPRESSION]: 400,
  [CLAW_SERVICE_ERROR_CODE.INVALID_CRON_EXPRESSION]: 400,
  [CLAW_SERVICE_ERROR_CODE.SCHEDULE_ALREADY_ACTIVE]: 409,
  [CLAW_SERVICE_ERROR_CODE.SCHEDULE_ALREADY_PAUSED]: 409,
  [CLAW_SERVICE_ERROR_CODE.SCHEDULE_HAS_ACTIVE_EXECUTIONS]: 409,
};

export class ClawServiceError extends DomainError {
  readonly statusCode: number;

  constructor(
    public readonly code: ClawServiceErrorCode,
    message: string,
    statusCode?: number,
  ) {
    super(message);
    this.statusCode = statusCode ?? DEFAULT_STATUS_BY_CODE[code] ?? 500;
  }
}

export function isClawServiceError(
  error: unknown,
): error is ClawServiceError {
  return error instanceof ClawServiceError;
}
