import { DomainError } from "./DomainError";

export const SETUP_SERVICE_ERROR_CODE = {
  KEY_FORMAT_INVALID: "KEY_FORMAT_INVALID",
  KEY_REJECTED: "KEY_REJECTED",
  KEY_FORBIDDEN: "KEY_FORBIDDEN",
  KEY_NO_CREDIT: "KEY_NO_CREDIT",
  KEY_RATE_LIMITED: "KEY_RATE_LIMITED",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  PROVIDER_UNREACHABLE: "PROVIDER_UNREACHABLE",
  NO_HARNESS_FOR_PROVIDER: "NO_HARNESS_FOR_PROVIDER",
  SECRET_MANAGED_ELSEWHERE: "SECRET_MANAGED_ELSEWHERE",
  REPOSITORY_INVALID: "REPOSITORY_INVALID",
  TOKEN_FORMAT_INVALID: "TOKEN_FORMAT_INVALID",
  TOKEN_REJECTED: "TOKEN_REJECTED",
  REPOSITORY_NOT_FOUND: "REPOSITORY_NOT_FOUND",
  REPOSITORY_FORBIDDEN: "REPOSITORY_FORBIDDEN",
  REPOSITORY_READ_ONLY: "REPOSITORY_READ_ONLY",
  GITHUB_RATE_LIMITED: "GITHUB_RATE_LIMITED",
  GITHUB_ERROR: "GITHUB_ERROR",
  GITHUB_UNREACHABLE: "GITHUB_UNREACHABLE",
  SPACE_NAME_INVALID: "SPACE_NAME_INVALID",
  SPACE_EXISTS: "SPACE_EXISTS",
  REPOSITORY_NOT_CONNECTED: "REPOSITORY_NOT_CONNECTED",
  MODEL_KEY_MISSING: "MODEL_KEY_MISSING",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
} as const;

export type SetupServiceErrorCode =
  (typeof SETUP_SERVICE_ERROR_CODE)[keyof typeof SETUP_SERVICE_ERROR_CODE];

const DEFAULT_STATUS_BY_CODE: Record<SetupServiceErrorCode, number> = {
  [SETUP_SERVICE_ERROR_CODE.KEY_FORMAT_INVALID]: 400,
  [SETUP_SERVICE_ERROR_CODE.KEY_REJECTED]: 422,
  [SETUP_SERVICE_ERROR_CODE.KEY_FORBIDDEN]: 422,
  [SETUP_SERVICE_ERROR_CODE.KEY_NO_CREDIT]: 422,
  [SETUP_SERVICE_ERROR_CODE.KEY_RATE_LIMITED]: 422,
  [SETUP_SERVICE_ERROR_CODE.PROVIDER_ERROR]: 502,
  [SETUP_SERVICE_ERROR_CODE.PROVIDER_UNREACHABLE]: 502,
  [SETUP_SERVICE_ERROR_CODE.NO_HARNESS_FOR_PROVIDER]: 500,
  [SETUP_SERVICE_ERROR_CODE.SECRET_MANAGED_ELSEWHERE]: 409,
  [SETUP_SERVICE_ERROR_CODE.REPOSITORY_INVALID]: 400,
  [SETUP_SERVICE_ERROR_CODE.TOKEN_FORMAT_INVALID]: 400,
  [SETUP_SERVICE_ERROR_CODE.TOKEN_REJECTED]: 422,
  [SETUP_SERVICE_ERROR_CODE.REPOSITORY_NOT_FOUND]: 422,
  [SETUP_SERVICE_ERROR_CODE.REPOSITORY_FORBIDDEN]: 422,
  [SETUP_SERVICE_ERROR_CODE.REPOSITORY_READ_ONLY]: 422,
  [SETUP_SERVICE_ERROR_CODE.GITHUB_RATE_LIMITED]: 422,
  [SETUP_SERVICE_ERROR_CODE.GITHUB_ERROR]: 502,
  [SETUP_SERVICE_ERROR_CODE.GITHUB_UNREACHABLE]: 502,
  [SETUP_SERVICE_ERROR_CODE.SPACE_NAME_INVALID]: 400,
  [SETUP_SERVICE_ERROR_CODE.SPACE_EXISTS]: 409,
  [SETUP_SERVICE_ERROR_CODE.REPOSITORY_NOT_CONNECTED]: 409,
  [SETUP_SERVICE_ERROR_CODE.MODEL_KEY_MISSING]: 409,
  [SETUP_SERVICE_ERROR_CODE.PROVIDER_UNAVAILABLE]: 400,
};

/** Setup failures; the message is shown to the person setting up, as is. */
export class SetupServiceError extends DomainError {
  readonly statusCode: number;

  constructor(
    public readonly code: SetupServiceErrorCode,
    message: string,
    statusCode?: number,
  ) {
    super(message);
    this.statusCode = statusCode ?? DEFAULT_STATUS_BY_CODE[code] ?? 500;
  }
}
