import { DomainError } from "./DomainError";

export const TICKET_SERVICE_ERROR_CODE = {
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  CLANKER_NOT_FOUND: "CLANKER_NOT_FOUND",
  INTEGRATION_CREDENTIAL_NOT_FOUND: "INTEGRATION_CREDENTIAL_NOT_FOUND",
  PROJECT_REPOSITORY_NOT_CONFIGURED: "PROJECT_REPOSITORY_NOT_CONFIGURED",
  CLANKER_DEPLOYMENT_STRATEGY_MISSING: "CLANKER_DEPLOYMENT_STRATEGY_MISSING",
  CLANKER_NOT_ACTIVE: "CLANKER_NOT_ACTIVE",
  EXECUTION_BLOCKED_UNAPPROVED_PLAN: "EXECUTION_BLOCKED_UNAPPROVED_PLAN",
  WORKFLOW_OVERRIDE_REASON_REQUIRED: "WORKFLOW_OVERRIDE_REASON_REQUIRED",
  WORKFLOW_ALREADY_OVERRIDDEN: "WORKFLOW_ALREADY_OVERRIDDEN",
  WORKFLOW_ALREADY_IN_EXECUTION: "WORKFLOW_ALREADY_IN_EXECUTION",
  RESEARCH_RUN_INVALID_PHASE: "RESEARCH_RUN_INVALID_PHASE",
  RESEARCH_APPROVAL_INVALID_PHASE: "RESEARCH_APPROVAL_INVALID_PHASE",
  PLANNING_RUN_INVALID_PHASE: "PLANNING_RUN_INVALID_PHASE",
  PLANNING_APPROVAL_REQUEST_INVALID_PHASE:
    "PLANNING_APPROVAL_REQUEST_INVALID_PHASE",
  PLANNING_APPROVAL_GRANT_INVALID_PHASE:
    "PLANNING_APPROVAL_GRANT_INVALID_PHASE",
} as const;

export type TicketServiceErrorCode =
  (typeof TICKET_SERVICE_ERROR_CODE)[keyof typeof TICKET_SERVICE_ERROR_CODE];

const DEFAULT_STATUS_BY_CODE: Record<TicketServiceErrorCode, number> = {
  [TICKET_SERVICE_ERROR_CODE.TICKET_NOT_FOUND]: 404,
  [TICKET_SERVICE_ERROR_CODE.CLANKER_NOT_FOUND]: 404,
  [TICKET_SERVICE_ERROR_CODE.INTEGRATION_CREDENTIAL_NOT_FOUND]: 404,
  [TICKET_SERVICE_ERROR_CODE.PROJECT_REPOSITORY_NOT_CONFIGURED]: 400,
  [TICKET_SERVICE_ERROR_CODE.CLANKER_DEPLOYMENT_STRATEGY_MISSING]: 400,
  [TICKET_SERVICE_ERROR_CODE.CLANKER_NOT_ACTIVE]: 400,
  [TICKET_SERVICE_ERROR_CODE.EXECUTION_BLOCKED_UNAPPROVED_PLAN]: 409,
  [TICKET_SERVICE_ERROR_CODE.WORKFLOW_OVERRIDE_REASON_REQUIRED]: 400,
  [TICKET_SERVICE_ERROR_CODE.WORKFLOW_ALREADY_OVERRIDDEN]: 409,
  [TICKET_SERVICE_ERROR_CODE.WORKFLOW_ALREADY_IN_EXECUTION]: 409,
  [TICKET_SERVICE_ERROR_CODE.RESEARCH_RUN_INVALID_PHASE]: 400,
  [TICKET_SERVICE_ERROR_CODE.RESEARCH_APPROVAL_INVALID_PHASE]: 409,
  [TICKET_SERVICE_ERROR_CODE.PLANNING_RUN_INVALID_PHASE]: 400,
  [TICKET_SERVICE_ERROR_CODE.PLANNING_APPROVAL_REQUEST_INVALID_PHASE]: 409,
  [TICKET_SERVICE_ERROR_CODE.PLANNING_APPROVAL_GRANT_INVALID_PHASE]: 409,
};

export class TicketServiceError extends DomainError {
  readonly statusCode: number;

  constructor(
    public readonly code: TicketServiceErrorCode,
    message: string,
    statusCode?: number,
  ) {
    super(message);
    this.statusCode = statusCode ?? DEFAULT_STATUS_BY_CODE[code] ?? 500;
  }
}

export function isTicketServiceError(
  error: unknown,
): error is TicketServiceError {
  return error instanceof TicketServiceError;
}

